env: "local"
http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
database: #TODO move this to ENV
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "password"
  db_name: "users"