env: "local"
http_server:
  address: "localhost:8090"
  timeout: 4s
  idle_timeout: 60s
database: #TODO move this to ENV
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  db_name: "users"